### PR TITLE
Backport classpath precedence

### PR DESCRIPTION
**Pull request by thekid**
See https://github.com/xp-framework/xp-runners/pull/39 (relevant for XP6)

_:warning: Needs real-life testing, unit tests don't cover all necessary paths_

### CODE REVIEW

**Comment by kiesel** [comment]
Unfortunately, this does not seem to work; the `autoload` section references files that either do not exist or are referenced with a wrong path. When fixed, *composer.json* would include a section like:

```json
  "autoload" : {
    "files" : ["core/tools/__xp.php", "core/src/main/php/autoload.php"]
  },
```

... and the *autoload.php* file would need to be created in the appropriate path. However, I have not succeeded in getting that to work because it doesn't work:

* with `core/tools/__xp.php` as first item, it ends up with `PHP Fatal error:  Cannot bootstrap class lang.Object` as the `src/main/php` path is available as classpath.

* with `src/main/php/autoload.php` as first item, to make it available as classpath **before** attempting to load classes from it, it fails with `PHP Fatal error:  Class 'lang\ClassLoader' not found...` as the class wasn't bootstrapped, yet, by `lang.base.php`.

**Comment by thekid** [comment]
Yes, I see:

```sh
Timm@slate ~/devel/xp-5x [backport/classpath-precedence]
$ XP_RT=5.6 USE_XP=core xp -cp core/tools/__xp.php -v

Fatal error: Cannot bootstrap class lang.Object
```

**Comment by thekid** [comment]
Please have a look after my changes, @kiesel. It would also be nice if you could describe your test setup and how to reproduce it with a bunch of shell commands (or a Dockerfile?), this would help greatly.

**Comment by thekid** [comment]
Figured out we can't make this work reliably... really, upgrade to XP7 (or XP6, if you must!)

**Pull request closed without merging**
