### PR TITLE
Add dataset generator namespaced

### PR DESCRIPTION
**Pull request by kiesel**
Copied version of non-namespaced generator template.

### CODE REVIEW

**Comment by kiesel** [comment]
This is not ready, yet.

**Comment by thekid** [comment]
Although not ready - very cool addition!

**Comment by johannes85** [comment]
I think at this point its better to backport this feature from XP6
https://github.com/xp-framework/xp-framework/pull/385

**Comment by kiesel** [comment]
Superseeded by #385

**Pull request closed without merging**
